[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphs_rsam1"
version = "0.1.0"
description = "A Python package implementing Dijkstra's algorithm"
authors = [{name = "RJ Sam", email = "rsam1@msudenver.edu"}]
readme = "README.md"
license = {text = "MIT"}
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

