[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphs_rsam1"
version = "0.1.0"
description = "A Python package for Dijkstra's algorithm"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
